import os
from string import ascii_letters, digits


class Config(object):
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')


LENGTH_LINK = 6
MAX_CUSTOM_LINK_LENGTH = 15
MAX_MODEL_ORIGINAL_LENGTH = 256
MAX_MODEL_SORT_LENGTH = 64
MAX_FORM_LENGTH_URL = 128
MAX_FORM_LENGTH_ID = 17
MIN_FORM_LENGTH = 1
CREATE_RANDOM_LINK = ascii_letters + digits
REGEX = r'^[a-zA-Z0-9]+$'
STATUS_CODE_OK = 200
STATUS_CODE_CREATED = 201
STATUS_CODE_BAD_REQUEST = 400
STATUS_CODE_NOT_FOUND = 404
STATUS_CODE_INTERNAL_ERROR = 500
